Improvement/test namnx228
Nordix/metal3-dev-env pull request #6
Opened 2019-08-05 08:21 UTC by namnx228

2019-08-05 13:39 UTC, maelk reviewed
Let's discuss about the use of roles

2019-08-05 13:39 UTC, maelk commented on vm-setup/roles/libvirt/tasks/install_setup_tasks.yml
> +  when: libvirt_action == "install_package"
Is this needed if it runs in 01 ? and starting libvirtd could be considered as an installation step

2019-08-05 13:39 UTC, maelk commented on vm-setup/roles/libvirt/tasks/main.yml
> +  when: libvirt_action == "setup"
unneeded space

2019-08-12 12:06 UTC, maelk requested changes

2019-08-12 12:06 UTC, maelk commented on vm-setup/install-package-playbook.yml
> +    - vars/input.yml
please use more explicit file naming

2019-08-12 12:06 UTC, maelk commented on vm-setup/install-package-playbook.yml
> +    install: "{{ input.packages_installation }}"
you can remove one level here

2019-08-12 12:06 UTC, maelk commented on vm-setup/roles/common/tasks/main.yml
> +  when: libvirt_action != "install_package"
remove this condition, it is not needed

2019-08-12 12:06 UTC, maelk commented on vm-setup/roles/packages_installation/tasks/main.yml
> +             name: "{{ install.centos.package + install.centos.libvirt.rhel7 }}"
rhel8 here

2019-08-12 12:06 UTC, maelk commented on vm-setup/vars/input.yml
> +input:
you can remove the input

2019-08-13 12:02 UTC, nordixinfra commented
Can one of the admins verify this patch?

2019-08-15 13:31 UTC, maelk requested changes

2019-08-15 13:31 UTC, maelk commented on vm-setup/roles/common/tasks/main.yml
> +  block:
why a block here ?

2019-08-15 13:31 UTC, maelk commented on vm-setup/roles/common/tasks/main.yml
> +  block:
This file should not be touched, right?

2019-08-15 13:35 UTC, maelk commented on vm-setup/vars/packages_installation.yml
> +    package:
packages

2019-08-15 13:35 UTC, maelk commented on vm-setup/vars/packages_installation.yml
> +    package:
packages

2019-08-15 13:35 UTC, maelk commented on vm-setup/roles/packages_installation/tasks/main.yml
> +        name: "{{ package.ubuntu.package +  package.ubuntu.libvirt }}"
packages (*3)

2019-08-15 13:35 UTC, maelk commented on vm-setup/roles/packages_installation/tasks/main.yml
> +        name: "{{ package.ubuntu.pip }}"
same and further in the file

2019-08-15 13:35 UTC, maelk commented on vm-setup/install-package-playbook.yml
> +    package: "{{ packages_installation }}"
packages

2019-10-29 13:39 UTC, maelk commented
we will not continue further in this direction for now

2019-10-29 13:39 UTC, closed without merging